import os, io, re
import streamlit as st
import pandas as pd
import openai
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
from time import sleep
from langchain_openai import ChatOpenAI
from langchain_core.messages import SystemMessage, HumanMessage
from typing import List, Dict, Any, Tuple
from dotenv import load_dotenv
import yaml

# === Configuration ===
load_dotenv()

# Load messages from the YAML file
# Ensure 'messages_v1.yaml' is available in the same directory or adjust path
try:
    with open('messages_v2.yaml', 'r') as file:
        MESSAGES = yaml.safe_load(file)
except FileNotFoundError:
    st.error("Error: messages_v1.yaml not found. Please ensure it's in the same directory.")
    st.stop()

# Initialize LangChain LLM for OpenAI models
llm_model = ChatOpenAI(model_name="gpt-4o") # Using gpt-4o as specified in v1.1

st.set_page_config(page_title="Fraud Pattern UI", layout="wide")
st.title("🔍 Fraud Pattern Explorer")

# Set OpenAI API key
# It's recommended to use st.secrets for API keys in a deployed app
openai.api_key = ""

# === Initialize Streamlit Session State ===
# This ensures that data persists across reruns of the app
if 'df' not in st.session_state:
    st.session_state.df = None
if 'filtered_df' not in st.session_state:
    st.session_state.filtered_df = None
if 'chat_history' not in st.session_state:
    st.session_state.chat_history = [] # Stores (question, response) tuples
if 'plots' not in st.session_state:
    st.session_state.plots = [] # Stores matplotlib/plotly figures generated by LLM

# Function to display LLM progress steps (visual indicator)
def show_llm_progress_steps():
    steps = [
        "🔍 Understanding query with Fraud Query Understanding Tool",
        "🧠 Generating intermediate code using Fraud Code Generation Tool",
        "🛡️ Generating fraud rule using Fraud Rule Generation Tool"
    ]
    st.markdown("<div style='display: flex; gap: 15px; margin-top: 1em;'>" +
                "".join([f"<div style='background-color:#e6f7ff; padding:10px; border-radius:5px;'>{step}</div>" for step in steps]) +
                "</div>", unsafe_allow_html=True)

# Function to explain fraud patterns based on the entire DataFrame
def explain_fraud(df_to_analyze: pd.DataFrame):
    if not openai.api_key:
        return "OpenAI API key not set."
    try:
        explanation = FraudDataInsightAgent(df_to_analyze)
        return explanation
    except Exception as e:
        show_llm_progress_steps() # Show progress even on error
        return f"LLM Error: {e}"

# Main function for interacting with the LLM (Fraud Assistant)
def chat_with_llm(user_q, current_df):
    if not openai.api_key:
        return "OpenAI API key not set."
    try:
        # Generate code based on user query and current (filtered) DataFrame
        code, should_plot_flag, code_thinking = FraudCodeGenerationAgent(user_q, current_df)
        
        # Execute the generated code
        result_obj = FraudExecutionAgent(code, current_df, should_plot_flag)
        
        # Reason about the result and extract patterns
        # Now, FraudReasoningAgent returns the full content, not streams to st
        raw_thinking, reasoning_txt, pattern_description = FraudReasoningAgent(user_q, result_obj)

        rule_suggestion = ""
        if pattern_description:
            rule_suggestion = FraudRuleGenerationAgent(pattern_description)
        
        # Build assistant response for display
        is_plot = isinstance(result_obj, (plt.Figure, plt.Axes))
        
        header = "" # Header is not directly used in the final response string, but can be for debugging
        if is_plot:
            fig = result_obj.figure if isinstance(result_obj, plt.Axes) else result_obj
            st.session_state.plots.append(fig) # Store the plot in session state
            header = "Here is the visualization you requested:"
        elif isinstance(result_obj, (pd.DataFrame, pd.Series)):
            header = f"Result: {len(result_obj)} rows" if isinstance(result_obj, pd.DataFrame) else "Result series"
        else:
            header = f"Result: {result_obj}"

        # Show only reasoning thinking in Model Thinking (collapsed by default)
        thinking_html = ""
        if raw_thinking:
            thinking_html = (
                    '<details class="thinking">'
                    '<summary>🧠 Reasoning</summary>'
                    f'<pre>{raw_thinking}</pre>'
                    '</details>'
                )

        # Show model explanation and pattern directly
        explanation_html = reasoning_txt
        if pattern_description:
            explanation_html += f"\n\n**Pattern Detected:** {pattern_description}"

        # Code accordion with proper HTML <pre><code> syntax highlighting
        code_html = (
                '<details class="code">'
                '<summary>View code</summary>'
                '<pre><code class="language-python">'
                f'{code}'
                '</code></pre>'
                '</details>'
            )
        
        # Combine all parts into a single response string
        full_response_content = f"{thinking_html}{explanation_html}\n\n{code_html}"
        
        # Store the question and response in chat history
        st.session_state.chat_history.append({"question": user_q, "response": full_response_content, "is_plot": is_plot})
        
        # No explicit st.write or st.markdown here, as the main loop will display from chat_history
        return "Response generated and added to chat history." # Acknowledge success
    except Exception as e:
        show_llm_progress_steps()
        st.session_state.chat_history.append({"question": user_q, "response": f"Chat Error: {e}", "is_plot": False})
        return f"Chat Error: {e}"
    
# === FraudCodeGeneration TOOLS ============================================

# ------------------ FraudQueryUnderstandingTool ---------------------------
def FraudQueryUnderstandingTool(query: str) -> bool:
    """Return True if the query seems to request a visualisation based on keywords."""
    messages = [
        SystemMessage(content=MESSAGES['fraud_query_understanding_tool']['system_message']),
        HumanMessage(content=query)
    ]

    response = llm_model.invoke(messages, config={"max_tokens": 5, "temperature": 0.1})

    intent_response = response.content.strip().lower()
    return intent_response == "true"

# === FraudCodeGeneration TOOLS ============================================

# ------------------ FraudPlotCodeGeneratorTool ---------------------------
def FraudPlotCodeGeneratorTool(cols: List[str], query: str) -> str:
    """Generate a prompt for the LLM to write pandas+matplotlib code for a plot based on the query and columns."""
    prompt_template = MESSAGES['fraud_plot_code_generator']['prompt']
    return prompt_template.format(cols=', '.join(cols), query=query)

# ------------------ FraudCodeWritingTool ---------------------------------
def FraudCodeWritingTool(cols: List[str], query: str) -> str:
    """Generate a prompt for the LLM to write pandas-only code for a data query (no plotting)."""
    prompt_template = MESSAGES['fraud_code_writing']['prompt']
    return prompt_template.format(cols=', '.join(cols), query=query)

# === FraudCodeGenerationAgent ==============================================
def FraudCodeGenerationAgent(query: str, df_to_analyze: pd.DataFrame):
    """Selects the appropriate code generation tool and gets code from the LLM for the user's query."""
    should_plot = FraudQueryUnderstandingTool(query)
    tool_name = "Fraud Plot Code Generator Tool" if should_plot else "Fraud Code Writing Tool"

    prompt_content = FraudPlotCodeGeneratorTool(df_to_analyze.columns.tolist(), query) if should_plot else FraudCodeWritingTool(df_to_analyze.columns.tolist(), query)

    messages = [
        SystemMessage(content=MESSAGES['fraud_code_generation_agent']['system_message']),
        HumanMessage(content=prompt_content)
    ]

    response = llm_model.invoke(messages, config={"max_tokens": 1024, "temperature": 0.2})

    full_response = response.content
    code = extract_first_code_block(full_response)
    return code, should_plot, ""


# === FraudQueryAssistantAgent ==============================================
def FraudQueryAssistantAgent(query: str):
    """Selects the appropriate code generation tool and gets code from the LLM for the user's query."""

    sample_data_str = excel_dict_to_text(st.session_state.df)
    prompt_content = MESSAGES['fraud_assistant_agent']['prompt'].format(sample_data=sample_data_str, query=query)


    messages = [
        SystemMessage(content=MESSAGES['fraud_assistant_agent']['system_message']),
        HumanMessage(content=prompt_content)
    ]

    response = llm_model.invoke(messages, config={"temperature": 0.2})

    print(response.content)
    return response.content

# === FraudExecutionAgent ====================================================
def FraudExecutionAgent(code: str, df_to_execute: pd.DataFrame, should_plot: bool):
    """Executes the generated code in a controlled environment and returns the result or error message."""
    env = {"pd": pd, "df": df_to_execute}
    if should_plot:
        plt.rcParams["figure.dpi"] = 100  # Set default DPI for all figures
        env["plt"] = plt
        env["io"] = io
    try:
        exec(code, {}, env)
        return env.get("result", None)
    except Exception as exc:
        return f"Error executing code: {exc}"

# === FraudReasoningCurator TOOL =========================================
def FraudReasoningCurator(query: str, result: Any) -> Tuple[str, bool, bool]:
    """Builds and returns the LLM prompt for reasoning about the result."""
    is_error = isinstance(result, str) and result.startswith("Error executing code")
    is_plot = isinstance(result, (plt.Figure, plt.Axes))

    if is_error:
        desc = result
    elif is_plot:
        title = ""
        if isinstance(result, plt.Figure):
            title = result._suptitle.get_text() if result._suptitle else ""
        elif isinstance(result, plt.Axes):
            title = result.get_title()
        desc = f"[Plot Object: {title or 'Chart'}]"
    else:
        desc = str(result)[:300]

    if is_plot:
        prompt = MESSAGES['fraud_reasoning_curator']['plot_description'].format(query=query, desc=desc)
    else:
        prompt = MESSAGES['fraud_reasoning_curator']['data_description'].format(query=query, desc=desc)
    return prompt, is_error, is_plot

# === FraudReasoningAgent (streaming) =========================================
def FraudReasoningAgent(query: str, result: Any):
    """Streams the LLM's reasoning about the result (plot or value) and extracts model 'thinking' and final explanation."""
    prompt_content, is_error, is_plot = FraudReasoningCurator(query, result)
    
    messages = [
        SystemMessage(content=MESSAGES['fraud_reasoning_agent']['system_message']),
        HumanMessage(content=prompt_content)
    ]

    response_generator = llm_model.stream(messages, config={"max_tokens": 1024, "temperature": 0.2})

    full_response = ""
    for chunk in response_generator:
        full_response += chunk.content

    # After streaming, extract final reasoning (outside <think>...</think>)
    thinking_match = re.search(r"<think>(.*?)</think>", full_response, flags=re.DOTALL)
    thinking_content = thinking_match.group(1).strip() if thinking_match else ""

    cleaned = re.sub(r"<think>.*?</think>", "", full_response, flags=re.DOTALL).strip()

    pattern_match = re.search(r"Pattern Detected: (.*)", cleaned, re.IGNORECASE)
    pattern_description = pattern_match.group(1).strip() if pattern_match else ""
    reasoning_without_pattern = re.sub(r"Pattern Detected:.*", "", cleaned, flags=re.DOTALL).strip()

    return thinking_content, reasoning_without_pattern, pattern_description


# === FraudRuleGenerationAgent =========================================
def FraudRuleGenerationAgent(pattern_description: str) -> str:
    """
    Uses the LLM to generate a simple 'IF [condition] THEN [action]' rule
    based on the identified fraud pattern.
    """
    if not pattern_description:
        return MESSAGES['fraud_rule_generation_agent']['no_pattern_message']

    prompt_content = MESSAGES['fraud_rule_generation_agent']['prompt'].format(pattern_description=pattern_description)
    messages = [
        SystemMessage(content=MESSAGES['fraud_rule_generation_agent']['system_message']),
        HumanMessage(content=prompt_content)
    ]

    try:
        response = llm_model.invoke(messages, config={"max_tokens": 100, "temperature": 0.1})
        return response.content.strip()
    except Exception as exc:
        return MESSAGES['fraud_rule_generation_agent']['error_message'].format(exc=exc)


# === FraudCustomerTimeline =========================================
def FraudCustomerTimelineAgent(df_to_summarizer) -> str:
    """
    Uses the LLM to generate a simple 'IF [condition] THEN [action]' rule
    based on the identified fraud pattern.
    """
    sample_data_str = excel_dict_to_text(df_to_summarizer)
    prompt_content = MESSAGES['fraud_dataframe_customer_timeline']['prompt'].format(sample_data=sample_data_str)
    messages = [
        SystemMessage(content=MESSAGES['fraud_code_generation_agent']['system_message']),
        HumanMessage(content=prompt_content)
    ]

    try:
        response = llm_model.invoke(messages, config={"temperature": 0.1})
        full_response = response.content
        code = extract_first_code_block(full_response)
        print(code)
        result_obj = FraudExecutionAgent(code, pd.DataFrame([df_to_summarizer]), False)
        return result_obj
    except Exception as exc:
        return MESSAGES['fraud_rule_generation_agent']['error_message'].format(exc=exc)


def excel_dict_to_text(sheet_dict: dict) -> str:
    """
    Converts a dictionary of DataFrames (from an Excel file with multiple sheets)
    into a readable text summary for LLM consumption.

    Args:
        sheet_dict (dict): Keys are sheet names, values are pandas DataFrames.
        max_rows_per_sheet (int): Number of rows to show per sheet.

    Returns:
        str: A formatted string representing the sheets, their columns, types, and sample data.
    """

    summary_lines = []

    for sheet_name, df in sheet_dict.items():
        summary_lines.append(f"\n=== Sheet: {sheet_name} ===")

        if df.empty:
            summary_lines.append("⚠️ Sheet is empty.\n")
            continue

        # Columns and data types
        col_info = ", ".join([f"{col} ({dtype})" for col, dtype in df.dtypes.items()])
        summary_lines.append(f"Columns: {col_info}")

        # Sample rows
        sample_text = df.to_markdown(index=False)
        summary_lines.append(f"Sample rows:\n{sample_text}")

    return "\n\n".join(summary_lines)


# === FraudDataFrameSummary TOOL (pandas only) =========================================
def FraudDataFrameSummaryTool(df_to_summarize) -> str:
    """Generate a summary prompt string for the LLM based on the DataFrame."""
    sample_data_str = excel_dict_to_text(df_to_summarize)
    print(sample_data_str)
    prompt = MESSAGES['fraud_dataframe_summary_tool']['prompt'].format(
        sample_data=sample_data_str
    )
    return prompt

# === FraudDataInsightAgent (upload-time only) ===============================
def FraudDataInsightAgent(df_to_insight) -> str:
    """Uses the LLM to generate a brief summary and possible questions for the uploaded dataset."""
    prompt_content = FraudDataFrameSummaryTool(df_to_insight)
    messages = [
        SystemMessage(content=MESSAGES['fraud_data_insight_agent']['system_message']),
        HumanMessage(content=prompt_content)
    ]
    try:
        response = llm_model.invoke(messages, config={"max_tokens": 512, "temperature": 0.2})
        return response.content
    except Exception as exc:
        return MESSAGES['fraud_data_insight_agent']['error_message'].format(exc=exc)

# === Helpers ===========================================================

def extract_first_code_block(text: str) -> str:
    """Extracts the first Python code block from a markdown-formatted string."""
    start = text.find("```python")
    if start == -1:
        return ""
    start += len("```python")
    end = text.find("```", start)
    if end == -1:
        return ""
    return text[start:end].strip()

# File uploader in the sidebar
uploaded_file = st.sidebar.file_uploader("Upload Excel file", type=["xlsx", "xls"]) # Changed accepted types

# Process uploaded file and store in session state
if uploaded_file:
    # Read the Excel and store in session state
    try:
        st.session_state.df = pd.read_excel(uploaded_file, sheet_name=None) # Changed to pd.read_excel()
        status_message = f"XLSX file loaded with sheets: {', '.join(st.session_state.df.keys())}"
        #print(pd.read_excel(uploaded_file))
        #print(st.session_state.df)
        #print(st.session_state.df.get("Customer"))
        #print(st.session_state.df.get("Events"))
        #print(st.session_state.df.get("Transaction"))

        # Extract individual DataFrames for merging
        df_customers = st.session_state.df.get("Customer")
        df_transactions = st.session_state.df.get("Transaction")
        df_events = st.session_state.df.get("Events")
        
        # Clear chat history and plots when a new file is uploaded
        st.session_state.chat_history = []
        st.session_state.plots = []
        
        st.success("File uploaded and processed successfully!")
    except Exception as e:
        st.error(f"Error reading Excel file: {e}. Please ensure it's a valid Excel format.")


# Only display the main app content if a DataFrame is loaded
if st.session_state.df is not None:
    

    st.subheader("📊 Fraud Overview")

    # Display Key Metrics using filtered_df from session state
    col_metrics_1, col_metrics_2, col_metrics_3, col_metrics_4 = st.columns(4)

    with col_metrics_1:
        st.metric(label="Total Transactions", value=len(st.session_state.df)) # Total loaded transactions

    st.markdown("---") # Separator

    st.subheader("🧠 Common Fraud Patterns Summary")
    with st.spinner("Analyzing common patterns..."):
        # The general summary (explain_fraud uses the full df, not filtered_df)
        st.write(explain_fraud(st.session_state.df))

    st.markdown("---") # Another separator before visualizations or other sections

    st.markdown("---") # Another separator before visualizations or other sections

    st.subheader("💬 Ask a question to the Fraud Assistant")
    st.markdown("**Suggested Questions:**")

    # Show suggested questions as text hints
    suggested_questions = [
    "What is the capital of France?",
    "How does Streamlit work?",
    "Explain machine learning in simple terms"
]

st.markdown("### 💡 Suggested Questions:")
for q in suggested_questions:
    st.markdown(f"- {q}")
    
    # Buttons for suggested questions
    for q in [
        "What are the most common fraud devices?",
        "Which IP addresses are used most often in fraud?",
        "What pattern is common among high-value frauds?"
    ]:
        if st.button(q, key=f"suggested_q_{q}"):
            with st.spinner("Analyzing your question..."):
                # Pass the currently filtered DataFrame to chat_with_llm
                st.write(FraudQueryAssistantAgent(q))
            # Removed st.experimental_rerun()

    # Text input for user's custom question
    user_input = st.text_input("Type your question here", key="user_question_input")
    if user_input:
        with st.spinner("Analyzing your question..."):
            # Pass the currently filtered DataFrame to chat_with_llm
            st.write(FraudQueryAssistantAgent(user_input))
        # Removed st.experimental_rerun()

    # Display chat history from session state
    if st.session_state.chat_history:
        st.markdown("---")
        st.subheader("Assistant Responses History")
        for i, entry in enumerate(st.session_state.chat_history):
            st.markdown(f"**Question:** {entry['question']}")
            st.markdown("**Assistant Response:**")
            st.write(entry['response'], unsafe_allow_html=True)
            # If the response included a plot, display it here
            if entry['is_plot'] and i < len(st.session_state.plots):
                st.pyplot(st.session_state.plots[i])
            st.markdown("---") # Separator between chat entries

else:
    st.info("Please upload an Excel file (.xlsx or .xls) with columns: Customer ID, Txn Amount, Device, IP Address, Fraud Type, Time, and Story (list of events as string).")