import os, io, re
import streamlit as st
import pandas as pd
import openai
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
from time import sleep
from langchain_openai import ChatOpenAI
from langchain_core.messages import SystemMessage, HumanMessage
from typing import List, Dict, Any, Tuple
from dotenv import load_dotenv
import yaml

# === Configuration ===
load_dotenv()

# Load messages from the YAML file
# Ensure 'messages_v1.yaml' is available in the same directory or adjust path
try:
    with open('messages_v1.yaml', 'r') as file:
        MESSAGES = yaml.safe_load(file)
except FileNotFoundError:
    st.error("Error: messages_v1.yaml not found. Please ensure it's in the same directory.")
    st.stop()

# Initialize LangChain LLM for OpenAI models
llm_model = ChatOpenAI(model_name="gpt-4o") # Using gpt-4o as specified in v1.1

st.set_page_config(page_title="Fraud Pattern UI", layout="wide")
st.title("🔍 Fraud Pattern Explorer")

# Set OpenAI API key
# It's recommended to use st.secrets for API keys in a deployed app
openai.api_key = ""

# === Initialize Streamlit Session State ===
# This ensures that data persists across reruns of the app
if 'df' not in st.session_state:
    st.session_state.df = None
if 'filtered_df' not in st.session_state:
    st.session_state.filtered_df = None
if 'chat_history' not in st.session_state:
    st.session_state.chat_history = [] # Stores (question, response) tuples
if 'plots' not in st.session_state:
    st.session_state.plots = [] # Stores matplotlib/plotly figures generated by LLM
# Removed 'user_question_input_value' as it's handled by st.form now

# Function to display LLM progress steps (visual indicator)
def show_llm_progress_steps():
    steps = [
        "🔍 Understanding query with Fraud Query Understanding Tool",
        "🧠 Generating intermediate code using Fraud Code Generation Tool",
        "🛡️ Generating fraud rule using Fraud Rule Generation Tool"
    ]
    st.markdown("<div style='display: flex; gap: 15px; margin-top: 1em;'>" +
                "".join([f"<div style='background-color:#e6f7ff; padding:10px; border-radius:5px;'>{step}</div>" for step in steps]) +
                "</div>", unsafe_allow_html=True)

# Function to explain fraud patterns based on the entire DataFrame
def explain_fraud(df_to_analyze: pd.DataFrame):
    if not openai.api_key:
        return "OpenAI API key not set."
    try:
        explanation = FraudDataInsightAgent(df_to_analyze)
        return explanation
    except Exception as e:
        show_llm_progress_steps() # Show progress even on error
        return f"LLM Error: {e}"

# Main function for interacting with the LLM (Fraud Assistant)
def chat_with_llm(user_q, current_df):
    if not openai.api_key:
        st.session_state.chat_history.append({"question": user_q, "response": "OpenAI API key not set.", "is_plot": False})
        return
    try:
        # Generate code based on user query and current (filtered) DataFrame
        code, should_plot_flag, code_thinking = FraudCodeGenerationAgent(user_q, current_df)
        
        # Execute the generated code
        result_obj = FraudExecutionAgent(code, current_df, should_plot_flag)
        
        # Reason about the result and extract patterns
        raw_thinking, reasoning_txt, pattern_description = FraudReasoningAgent(user_q, result_obj)

        rule_suggestion = ""
        if pattern_description:
            rule_suggestion = FraudRuleGenerationAgent(pattern_description)
        
        # Build assistant response for display
        is_plot = isinstance(result_obj, (plt.Figure, plt.Axes))
        
        if is_plot:
            fig = result_obj.figure if isinstance(result_obj, plt.Axes) else result_obj
            st.session_state.plots.append(fig) # Store the plot in session state

        # Show only reasoning thinking in Model Thinking (collapsed by default)
        thinking_html = ""
        if raw_thinking:
            thinking_html = (
                    '<details class="thinking">'
                    '<summary>🧠 Reasoning</summary>'
                    f'<pre>{raw_thinking}</pre>'
                    '</details>'
                )

        # Show model explanation and pattern directly
        explanation_html = reasoning_txt
        if pattern_description:
            explanation_html += f"\n\n**Pattern Detected:** {pattern_description}"

        # Code accordion with proper HTML <pre><code> syntax highlighting
        code_html = (
                '<details class="code">'
                '<summary>View code</summary>'
                '<pre><code class="language-python">'
                f'{code}'
                '</code></pre>'
                '</details>'
            )
        
        # Combine all parts into a single response string
        full_response_content = f"{thinking_html}{explanation_html}\n\n{code_html}"
        
        # Store the question and response in chat history
        st.session_state.chat_history.append({"question": user_q, "response": full_response_content, "is_plot": is_plot})
        
    except Exception as e:
        show_llm_progress_steps()
        st.session_state.chat_history.append({"question": user_q, "response": f"Chat Error: {e}", "is_plot": False})
    
# === Callback functions for button clicks and text input submission ===
# Simplified for st.form integration
def handle_suggested_question(q):
    with st.spinner("Analyzing your question..."):
        chat_with_llm(q, st.session_state.filtered_df)
    # No st.experimental_rerun() needed, Streamlit's natural re-render will occur

# === FraudCodeGeneration TOOLS ============================================

# ------------------ FraudQueryUnderstandingTool ---------------------------
def FraudQueryUnderstandingTool(query: str) -> bool:
    """Return True if the query seems to request a visualisation based on keywords."""
    messages = [
        SystemMessage(content=MESSAGES['fraud_query_understanding_tool']['system_message']),
        HumanMessage(content=query)
    ]

    response = llm_model.invoke(messages, config={"max_tokens": 5, "temperature": 0.1})

    intent_response = response.content.strip().lower()
    return intent_response == "true"

# === FraudCodeGeneration TOOLS ============================================

# ------------------ FraudPlotCodeGeneratorTool ---------------------------
def FraudPlotCodeGeneratorTool(cols: List[str], query: str) -> str:
    """Generate a prompt for the LLM to write pandas+matplotlib code for a plot based on the query and columns."""
    prompt_template = MESSAGES['fraud_plot_code_generator']['prompt']
    return prompt_template.format(cols=', '.join(cols), query=query)

# ------------------ FraudCodeWritingTool ---------------------------------
def FraudCodeWritingTool(cols: List[str], query: str) -> str:
    """Generate a prompt for the LLM to write pandas-only code for a data query (no plotting)."""
    prompt_template = MESSAGES['fraud_code_writing']['prompt']
    return prompt_template.format(cols=', '.join(cols), query=query)

# === FraudCodeGenerationAgent ==============================================
def FraudCodeGenerationAgent(query: str, df_to_analyze: pd.DataFrame):
    """Selects the appropriate code generation tool and gets code from the LLM for the user's query."""
    should_plot = FraudQueryUnderstandingTool(query)
    tool_name = "Fraud Plot Code Generator Tool" if should_plot else "Fraud Code Writing Tool"

    prompt_content = FraudPlotCodeGeneratorTool(df_to_analyze.columns.tolist(), query) if should_plot else FraudCodeWritingTool(df_to_analyze.columns.tolist(), query)

    messages = [
        SystemMessage(content=MESSAGES['fraud_code_generation_agent']['system_message']),
        HumanMessage(content=prompt_content)
    ]

    response = llm_model.invoke(messages, config={"max_tokens": 1024, "temperature": 0.2})

    full_response = response.content
    code = extract_first_code_block(full_response)
    return code, should_plot, ""

# === FraudExecutionAgent ====================================================
def FraudExecutionAgent(code: str, df_to_execute: pd.DataFrame, should_plot: bool):
    """Executes the generated code in a controlled environment and returns the result or error message."""
    env = {"pd": pd, "df": df_to_execute}
    if should_plot:
        plt.rcParams["figure.dpi"] = 100  # Set default DPI for all figures
        env["plt"] = plt
        env["io"] = io
    try:
        exec(code, {}, env)
        return env.get("result", None)
    except Exception as exc:
        return f"Error executing code: {exc}"

# === FraudReasoningCurator TOOL =========================================
def FraudReasoningCurator(query: str, result: Any) -> Tuple[str, bool, bool]:
    """Builds and returns the LLM prompt for reasoning about the result."""
    is_error = isinstance(result, str) and result.startswith("Error executing code")
    is_plot = isinstance(result, (plt.Figure, plt.Axes))

    if is_error:
        desc = result
    elif is_plot:
        title = ""
        if isinstance(result, plt.Figure):
            title = result._suptitle.get_text() if result._suptitle else ""
        elif isinstance(result, plt.Axes):
            title = result.get_title()
        desc = f"[Plot Object: {title or 'Chart'}]"
    else:
        desc = str(result)[:300]

    if is_plot:
        prompt = MESSAGES['fraud_reasoning_curator']['plot_description'].format(query=query, desc=desc)
    else:
        prompt = MESSAGES['fraud_reasoning_curator']['data_description'].format(query=query, desc=desc)
    return prompt, is_error, is_plot

# === FraudReasoningAgent (streaming) =========================================
def FraudReasoningAgent(query: str, result: Any):
    """Streams the LLM's reasoning about the result (plot or value) and extracts model 'thinking' and final explanation."""
    prompt_content, is_error, is_plot = FraudReasoningCurator(query, result)
    
    messages = [
        SystemMessage(content=MESSAGES['fraud_reasoning_agent']['system_message']),
        HumanMessage(content=prompt_content)
    ]

    response_generator = llm_model.stream(messages, config={"max_tokens": 1024, "temperature": 0.2})

    full_response = ""
    for chunk in response_generator:
        full_response += chunk.content

    # After streaming, extract final reasoning (outside <think>...</think>)
    thinking_match = re.search(r"<think>(.*?)</think>", full_response, flags=re.DOTALL)
    thinking_content = thinking_match.group(1).strip() if thinking_match else ""

    cleaned = re.sub(r"<think>.*?</think>", "", full_response, flags=re.DOTALL).strip()

    pattern_match = re.search(r"Pattern Detected: (.*)", cleaned, re.IGNORECASE)
    pattern_description = pattern_match.group(1).strip() if pattern_match else ""
    reasoning_without_pattern = re.sub(r"Pattern Detected:.*", "", cleaned, flags=re.DOTALL).strip()

    return thinking_content, reasoning_without_pattern, pattern_description


# === FraudRuleGenerationAgent =========================================
def FraudRuleGenerationAgent(pattern_description: str) -> str:
    """
    Uses the LLM to generate a simple 'IF [condition] THEN [action]' rule
    based on the identified fraud pattern.
    """
    if not pattern_description:
        return MESSAGES['fraud_rule_generation_agent']['no_pattern_message']

    prompt_content = MESSAGES['fraud_rule_generation_agent']['prompt'].format(pattern_description=pattern_description)
    messages = [
        SystemMessage(content=MESSAGES['fraud_rule_generation_agent']['system_message']),
        HumanMessage(content=prompt_content)
    ]

    try:
        response = llm_model.invoke(messages, config={"max_tokens": 100, "temperature": 0.1})
        return response.content.strip()
    except Exception as exc:
        return MESSAGES['fraud_rule_generation_agent']['error_message'].format(exc=exc)


# === FraudDataFrameSummary TOOL (pandas only) =========================================
def FraudDataFrameSummaryTool(df_to_summarize: pd.DataFrame) -> str:
    """Generate a summary prompt string for the LLM based on the DataFrame."""
    prompt = MESSAGES['fraud_dataframe_summary_tool']['prompt'].format(
        num_rows=len(df_to_summarize),
        num_cols=len(df_to_summarize.columns),
        data_types=df_to_summarize.dtypes.to_dict(),
        sample_data=df_to_summarize.head(10).to_csv(index=False)
    )
    return prompt

# === FraudDataInsightAgent (upload-time only) ===============================
def FraudDataInsightAgent(df_to_insight: pd.DataFrame) -> str:
    """Uses the LLM to generate a brief summary and possible questions for the uploaded dataset."""
    prompt_content = FraudDataFrameSummaryTool(df_to_insight)
    messages = [
        SystemMessage(content=MESSAGES['fraud_data_insight_agent']['system_message']),
        HumanMessage(content=prompt_content)
    ]
    try:
        response = llm_model.invoke(messages, config={"max_tokens": 512, "temperature": 0.2})
        return response.content
    except Exception as exc:
        return MESSAGES['fraud_data_insight_agent']['error_message'].format(exc=exc)

# === Helpers ===========================================================

def extract_first_code_block(text: str) -> str:
    """Extracts the first Python code block from a markdown-formatted string."""
    start = text.find("```python")
    if start == -1:
        return ""
    start += len("```python")
    end = text.find("```", start)
    if end == -1:
        return ""
    return text[start:end].strip()

# File uploader in the sidebar
uploaded_file = st.sidebar.file_uploader("Upload CSV file", type=["csv"])

# Process uploaded file and store in session state
if uploaded_file:
    # Read the CSV and store in session state
    st.session_state.df = pd.read_csv(uploaded_file)
    
    # Convert 'Time' column to datetime if it exists
    if 'Time' in st.session_state.df.columns:
        st.session_state.df['Time'] = pd.to_datetime(st.session_state.df['Time'], errors='coerce')
    
    # Initialize filtered_df with the full df upon upload
    st.session_state.filtered_df = st.session_state.df.copy()
    
    # Clear chat history and plots when a new file is uploaded
    st.session_state.chat_history = []
    st.session_state.plots = []
    
    st.success("File uploaded and processed successfully!")

# Only display the main app content if a DataFrame is loaded
if st.session_state.df is not None:
    st.sidebar.header("Filters")

    # Get unique customer IDs and fraud types from the *original* DataFrame for filter options
    customer_ids = st.session_state.df['Customer ID'].dropna().unique()
    sorted_customer_ids = sorted(customer_ids.astype(str))
    selected_customer = st.sidebar.selectbox("Select Customer ID", options=["All"] + sorted_customer_ids, key="customer_filter")

    fraud_types = st.session_state.df["Fraud Type"].dropna().unique()
    selected_fraud = st.sidebar.selectbox("Select Fraud Type", options=["All"] + sorted(fraud_types), key="fraud_type_filter")

    min_date = st.session_state.df['Time'].min().date() if 'Time' in st.session_state.df.columns and not st.session_state.df['Time'].empty else None
    max_date = st.session_state.df['Time'].max().date() if 'Time' in st.session_state.df.columns and not st.session_state.df['Time'].empty else None

    # Handle cases where min_date or max_date might be NaT or None
    if min_date is None:
        start_date = st.sidebar.date_input("Start Date", value=None, disabled=True, key="start_date_filter")
    else:
        start_date = st.sidebar.date_input("Start Date", min_value=min_date, value=min_date, key="start_date_filter")
    
    if max_date is None:
        end_date = st.sidebar.date_input("End Date", value=None, disabled=True, key="end_date_filter")
    else:
        end_date = st.sidebar.date_input("End Date", min_value=min_date, value=max_date, key="end_date_filter")

    # Apply filters and update filtered_df in session state
    temp_filtered_df = st.session_state.df.copy()
    if selected_customer != "All":
        temp_filtered_df = temp_filtered_df[temp_filtered_df["Customer ID"].astype(str) == selected_customer]
    if selected_fraud != "All":
        temp_filtered_df = temp_filtered_df[temp_filtered_df["Fraud Type"] == selected_fraud]
    
    if 'Time' in temp_filtered_df.columns and start_date and end_date:
        start_datetime = pd.to_datetime(start_date)
        end_datetime = pd.to_datetime(end_date) + pd.Timedelta(days=1) - pd.Timedelta(seconds=1) # Include full end day
        temp_filtered_df = temp_filtered_df[(temp_filtered_df['Time'] >= start_datetime) & (temp_filtered_df['Time'] <= end_datetime)]
    
    st.session_state.filtered_df = temp_filtered_df # Update the filtered_df in session state

    st.subheader("📊 Fraud Overview")

    # Display Key Metrics using filtered_df from session state
    col_metrics_1, col_metrics_2, col_metrics_3, col_metrics_4 = st.columns(4)

    with col_metrics_1:
        st.metric(label="Total Transactions", value=len(st.session_state.df)) # Total loaded transactions
    with col_metrics_2:
        st.metric(label="Total Fraud Cases", value=len(st.session_state.filtered_df)) # Fraud cases after filters
    with col_metrics_3:
        if 'Customer ID' in st.session_state.filtered_df.columns:
            st.metric(label="Unique Fraud Customers", value=st.session_state.filtered_df['Customer ID'].nunique())
        else:
            st.metric(label="Unique Fraud Customers", value="N/A")
    with col_metrics_4:
        if 'Txn Amount' in st.session_state.filtered_df.columns:
            st.metric(label="Total Fraud Amount", value=f"${st.session_state.filtered_df['Txn Amount'].sum():,.2f}")
        else:
            st.metric(label="Total Fraud Amount", value="N/A")

    st.markdown("---") # Separator

    st.subheader("🧠 Common Fraud Patterns Summary")
    with st.spinner("Analyzing common patterns..."):
        # The general summary (explain_fraud uses the full df, not filtered_df)
        st.write(explain_fraud(st.session_state.df))

    st.markdown("---") # Another separator before visualizations or other sections

    st.subheader("💬 Ask a question to the Fraud Assistant")
    st.markdown("**Suggested Questions:**")
    
    # Buttons for suggested questions
    for q in [
        "What are the most common fraud devices?",
        "Which IP addresses are used most often in fraud?",
        "What pattern is common among high-value frauds?"
    ]:
        st.button(q, on_click=handle_suggested_question, args=(q,), key=f"suggested_q_{q}")

    # Text input for user's custom question within a form
    with st.form("chat_form", clear_on_submit=True):
        user_question = st.text_input("Type your question here", key="user_question_input_key")
        submitted = st.form_submit_button("Send") # This button enables submission by Enter key

        if submitted and user_question:
            with st.spinner("Analyzing your question..."):
                chat_with_llm(user_question, st.session_state.filtered_df)
            # No st.experimental_rerun() needed here, form submission handles rerun

    # Display chat history from session state
    if st.session_state.chat_history:
        st.markdown("---")
        st.subheader("Assistant Responses History")
        for i, entry in enumerate(st.session_state.chat_history):
            st.markdown(f"**Question:** {entry['question']}")
            st.markdown("**Assistant Response:**")
            st.write(entry['response'], unsafe_allow_html=True)
            # If the response included a plot, display it here
            if entry['is_plot'] and i < len(st.session_state.plots):
                st.pyplot(st.session_state.plots[i])
            st.markdown("---") # Separator between chat entries

    st.markdown("---") # Another separator before visualizations or other sections
    with st.expander("📈 Visualize Fraud Patterns", expanded=False):
        col1, col2 = st.columns(2)
        with col1:
            if 'Fraud Type' in st.session_state.filtered_df.columns and not st.session_state.filtered_df.empty:
                st.markdown("**Fraud Count by Type**")
                fig1, ax1 = plt.subplots()
                sns.countplot(data=st.session_state.filtered_df, x='Fraud Type', ax=ax1)
                ax1.set_title("Fraud Cases by Type")
                ax1.tick_params(axis='x', rotation=45)
                st.pyplot(fig1)
            else:
                st.info("No 'Fraud Type' data or filtered data to visualize.")

        with col2:
            if 'Time' in st.session_state.filtered_df.columns and not st.session_state.filtered_df.empty:
                st.markdown("**Fraud Over Time**")
                time_series = st.session_state.filtered_df.set_index('Time').resample('D').size()
                fig2, ax2 = plt.subplots()
                time_series.plot(ax=ax2)
                ax2.set_title("Fraud Cases Over Time")
                ax2.set_ylabel("Cases")
                st.pyplot(fig2)
            else:
                st.info("No 'Time' data or filtered data to visualize.")

        st.markdown("---")
        if 'Fraud Type' in st.session_state.filtered_df.columns and 'Txn Amount' in st.session_state.filtered_df.columns and not st.session_state.filtered_df.empty:
            st.markdown("**Box Plot - Txn Amount by Fraud Type**")
            fig3 = px.box(st.session_state.filtered_df, x='Fraud Type', y='Txn Amount', title="Transaction Amount Distribution by Fraud Type")
            st.plotly_chart(fig3)
        else:
            st.info("Missing 'Fraud Type' or 'Txn Amount' for Box Plot, or no filtered data.")

        if 'Device' in st.session_state.filtered_df.columns and 'Fraud Type' in st.session_state.filtered_df.columns and not st.session_state.filtered_df.empty:
            st.markdown("**Device Usage by Fraud Type**")
            fig4 = px.histogram(st.session_state.filtered_df, x='Device', color='Fraud Type', barmode='group', title="Device Usage by Fraud Type")
            st.plotly_chart(fig4)
        else:
            st.info("Missing 'Device' or 'Fraud Type' for Device Usage plot, or no filtered data.")

        if 'IP Address' in st.session_state.filtered_df.columns and not st.session_state.filtered_df.empty:
            st.markdown("**Top IP Addresses Involved in Fraud**")
            top_ips = st.session_state.filtered_df['IP Address'].value_counts().head(10).reset_index()
            top_ips.columns = ['IP Address', 'Count']
            fig5 = px.bar(top_ips, x='IP Address', y='Count', title="Top 10 IPs in Fraudulent Transactions")
            st.plotly_chart(fig5)
        else:
            st.info("Missing 'IP Address' for Top IPs plot, or no filtered data.")

    st.markdown("---") # Another separator before visualizations or other sections
    st.subheader("Fraudulent Transactions")
    if not st.session_state.filtered_df.empty:
        for index, row in st.session_state.filtered_df.iterrows():
            with st.expander(f"🧾 Customer ID: {row['Customer ID']} | {row['Fraud Type']} | ${row['Txn Amount']}"):
                st.write(f"**Device:** {row.get('Device', 'N/A')}")
                st.write(f"**IP Address:** {row.get('IP Address', 'N/A')}")
                st.write(f"**Time:** {row.get('Time', 'N/A')}")
                if isinstance(row.get('Story'), str):
                    try:
                        events = eval(row['Story']) # Using eval() can be risky with untrusted input
                        if isinstance(events, list):
                            st.markdown("**Event Timeline:**")
                            for event in events:
                                st.markdown(f"- {event}")
                            # The original code called chat_with_llm here, which adds to history.
                            # If you want a separate, non-history-logging explanation here,
                            # you might call explain_fraud directly or a modified version.
                            # For now, I'll assume you want to keep the chat history clean
                            # and only add explicit user questions to it.
                            # If you need LLM explanation for each expanded transaction,
                            # consider adding a button to trigger it.
                            # Example:
                            # if st.button(f"Explain Fraud for {row['Customer ID']}", key=f"explain_{row['Customer ID']}"):
                            #     with st.spinner("Analyzing pattern..."):
                            #         explanation = explain_fraud_for_single_txn(row) # A new function for single txn
                            #         st.markdown("**LLM Explanation:**")
                            #         st.write(explanation)
                    except Exception as e: # Catch specific parsing errors if possible
                        st.warning(f"Story format for Customer ID {row['Customer ID']} is not a valid list: {e}")
    else:
        st.info("No fraudulent transactions to display based on current filters.")

else:
    st.info("Please upload a CSV file with columns: Customer ID, Txn Amount, Device, IP Address, Fraud Type, Time, and Story (list of events as string).")
